-- Application data is accessed through the Express server, never client Data API roles.
-- The server's postgres connection retains access; no client policies are needed.
ALTER TABLE public.admission_applications ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.admission_applications FROM anon, authenticated, PUBLIC;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.announcements FROM anon, authenticated, PUBLIC;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.attendance FROM anon, authenticated, PUBLIC;
ALTER TABLE public.class_subjects ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.class_subjects FROM anon, authenticated, PUBLIC;
ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.classes FROM anon, authenticated, PUBLIC;
ALTER TABLE public.exam_subjects ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.exam_subjects FROM anon, authenticated, PUBLIC;
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.exams FROM anon, authenticated, PUBLIC;
ALTER TABLE public.fee_types ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.fee_types FROM anon, authenticated, PUBLIC;
ALTER TABLE public.finance_records ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.finance_records FROM anon, authenticated, PUBLIC;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.payments FROM anon, authenticated, PUBLIC;
ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.results FROM anon, authenticated, PUBLIC;
ALTER TABLE public.schools ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.schools FROM anon, authenticated, PUBLIC;
ALTER TABLE public.sections ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.sections FROM anon, authenticated, PUBLIC;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.staff FROM anon, authenticated, PUBLIC;
ALTER TABLE public.student_fees ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.student_fees FROM anon, authenticated, PUBLIC;
ALTER TABLE public.student_guardians ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.student_guardians FROM anon, authenticated, PUBLIC;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.students FROM anon, authenticated, PUBLIC;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.subjects FROM anon, authenticated, PUBLIC;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.teachers FROM anon, authenticated, PUBLIC;
ALTER TABLE public.timetable ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.timetable FROM anon, authenticated, PUBLIC;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.users FROM anon, authenticated, PUBLIC;
ALTER TABLE public.website_content ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.website_content FROM anon, authenticated, PUBLIC;
ALTER TABLE public.website_gallery ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.website_gallery FROM anon, authenticated, PUBLIC;
ALTER TABLE public.website_news ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.website_news FROM anon, authenticated, PUBLIC;
