const PDFDocument = require('pdfkit');

function renderReceiptPdf(res, receipt) {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="receipt-${receipt.receipt_no}.pdf"`);
  const doc = new PDFDocument({ size: 'A5', margin: 40 });
  doc.pipe(res);

  doc.fontSize(18).text(receipt.school_name || 'School', { align: 'center' });
  doc.moveDown(0.2);
  doc.fontSize(10).fillColor('#555').text(receipt.address || '', { align: 'center' });
  doc.moveDown(1);
  doc.fillColor('#000').fontSize(14).text('Payment Receipt', { align: 'center', underline: true });
  doc.moveDown(1);

  const line = (label, value) => {
    doc.fontSize(11).text(`${label}: `, { continued: true, }).font('Helvetica-Bold').text(String(value)).font('Helvetica');
  };

  line('Receipt No', receipt.receipt_no);
  line('Date', receipt.payment_date);
  line('Student', `${receipt.first_name} ${receipt.last_name || ''}`.trim());
  line('Admission No', receipt.admission_no);
  line('Amount', `${receipt.currency || ''} ${Number(receipt.amount).toFixed(2)}`);
  line('Method', receipt.method);
  if (receipt.notes) line('Notes', receipt.notes);

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#888').text('This is a system-generated receipt.', { align: 'center' });
  doc.end();
}

function renderReportCardPdf(res, data) {
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="report-card.pdf"`);
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  doc.pipe(res);

  doc.fontSize(20).text(data.school.name || 'School', { align: 'center' });
  if (data.school.report_card_header) {
    doc.fontSize(10).fillColor('#555').text(data.school.report_card_header, { align: 'center' });
  }
  doc.moveDown(0.5);
  doc.fillColor('#000').fontSize(14).text('Report Card', { align: 'center', underline: true });
  doc.moveDown(1);

  doc.fontSize(11);
  doc.text(`Student: ${data.student.first_name} ${data.student.last_name || ''}`);
  doc.text(`Admission No: ${data.student.admission_no}`);
  doc.text(`Class: ${data.exam.class_name}   Section: ${data.student.section_name || '-'}`);
  doc.text(`Exam: ${data.exam.name} (${data.exam.term || ''})`);
  doc.moveDown(1);

  const tableTop = doc.y;
  const colX = [50, 260, 340, 420, 490];
  doc.font('Helvetica-Bold');
  doc.text('Subject', colX[0], tableTop);
  doc.text('Max', colX[1], tableTop);
  doc.text('Obtained', colX[2], tableTop);
  doc.text('Grade', colX[3], tableTop);
  doc.font('Helvetica');
  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.3);

  for (const s of data.subjects) {
    const y = doc.y;
    doc.text(s.subject_name, colX[0], y);
    doc.text(String(s.max_marks), colX[1], y);
    doc.text(s.marks_obtained == null ? '-' : String(s.marks_obtained), colX[2], y);
    doc.text(s.grade || '-', colX[3], y);
    doc.moveDown(0.6);
  }

  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.8);
  doc.font('Helvetica-Bold');
  doc.text(`Total: ${data.totalObtained} / ${data.totalMax}`);
  doc.text(`Average: ${data.average == null ? '-' : data.average + '%'}`);
  doc.text(`Grade: ${data.grade || '-'}`);
  doc.font('Helvetica');
  doc.text(`Attendance: ${data.attendancePercentage == null ? '-' : data.attendancePercentage + '%'}`);

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#888').text('This report card was generated by the school management system.', { align: 'center' });
  doc.end();
}

module.exports = { renderReceiptPdf, renderReportCardPdf };
